### ISSUE TITLE
"Failed to load the ec_sys kernel module" on OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by THGROfficial** [dmitry-s93/MControlCenter#116]
I wanted to let you know that I recently updated my kernel to 6.4.3-1.1 on Tumbleweed and since then the program throws this error every time it lauches. Obviously none of the functions work anymore and it's become redundant.

**Comment by dmitry-s93** [comment]
Hello. Disabling Secure Boot in BIOS settings solves this problem.

**Comment by Radical4ever** [comment]
ok, so for me this doesnt work at all, im on fedora 38 with kernel 6.4.4 and trying to enabe ex_sys doesnt work `modprobe: FATAL: Module ec_sys not found in directory /lib/modules/6.4.4-200.fc38.x86_64`

**Comment by Radical4ever** [comment]
but how can i solve this, should i enable acpi_ec and of that's the case how?

**Comment by dmitry-s93** [comment]
> but how can i solve this, should i enable acpi_ec and of that's the case how?

Fedora does not include the ec_sys kernel module. Try acpi_ec. This should work.

**Comment by Radical4ever** [comment]
> > but how can i solve this, should i enable acpi_ec and of that's the case how?
> 
> Fedora does not include the ec_sys kernel module. Try acpi_ec. This should work.

i tried installing it, it doesnt work, trying with a fork updated for kernel 6.4.4 drops me the next message `fatal: No names found, nothing can be described.`

**Comment by Radical4ever** [comment]
all of this is on fedora, an my pc has secureboot disabled

**Comment by Radical4ever** [comment]
ok so i already have installer de version 1.0.2 of acpi_ec but still drops me the same message as the title of this error

**Comment by dmitry-s93** [comment]
Check that the /dev/ec file exists. If not, then acpi_ec is not installed properly.

**Comment by Radical4ever** [comment]
> Check that the /dev/ec file exists. If not, then acpi_ec is not installed properly.

no, it doesnt appear i tried installing it but it appears the next thing:
`./install.sh
WARNING: Secure Boot is not enabled!
Error! DKMS tree already contains: acpi_ec-v1.0.2
You cannot add the same module/version combo more than once.`

but running uninstall.sh drops me the next thing:

Module acpi_ec-v1.0.2 for kernel 6.4.4-200.fc38.x86_64 (x86_64).
Before uninstall, this module version was ACTIVE on this kernel.
acpi_ec.ko.xz:
 -Uninstallation
   - Deleting from: /lib/modules/6.4.4-200.fc38.x86_64/extra/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.
depmod.....
Module acpi_ec v1.0.2 is not installed for kernel 6.4.4-200.fc38.x86_64 (x86_64). Skipping...

**Comment by Radical4ever** [comment]
> Check that the /dev/ec file exists. If not, then acpi_ec is not installed properly.

ok so i removed some files put it wrong and reinstalled the kernel, some of them on the dkms folder and some symlinks and reinstalled the script again, i rebooted and now everything works fine!

**Comment by atepookie** [comment]
> i removed some files

what files did you remove? i tried to uninstall and reinstall, but nothing worked :(
