### ISSUE TITLE
Not working for MSI GF63 Thin 11UC with Fedora 39

### ISSUE THREAD

**Issue by ismailgamedev** [dmitry-s93/MControlCenter#140]
I was tried with Manjaro. Its worked but now im traying with Fedora 39 not working 
![image](https://github.com/dmitry-s93/MControlCenter/assets/64804972/4c7a33ad-22c8-43f5-9588-03c23b05610e)

**Comment by ismailgamedev** [comment]
![image](https://github.com/dmitry-s93/MControlCenter/assets/64804972/2a2474e0-f3ca-44bb-98cf-4db89c2414d5)
Also im getting error like this

**Comment by ismailgamedev** [comment]
I installed aspi_ec modulle and its worked for me

**Comment by atepookie** [comment]
https://github.com/FaridZelli/ISW-Modern

use this instructions to install acpi_ec
