### ISSUE TITLE
List of supported devices?

### ISSUE THREAD

**Issue by 15placek** [dmitry-s93/MControlCenter#17]
Would be useful to have some sort of information on what models are supported before i try to use this on my GL73 8RC.

**Comment by dmitry-s93** [comment]
So far, the application has only been tested on the MSI Summit E16 Flip Evo. When the application starts, the current values in the EC are checked for those known to the application. If the value differs from the known ones, then the function control will be disabled.

You can try this on your laptop. If something does not work, but is supported by a laptop, a description of the problem and an EC dump will be required.
