### ISSUE TITLE
ec_sys installed but still says "ec_sys module failed to load"

### ISSUE THREAD

**Issue by thecodsman** [dmitry-s93/MControlCenter#173]
lsmod | grep "ec_sys" gives `ec_sys                 12288  0`
my distro is artix linux (runit)

**Comment by thecodsman** [comment]
my laptop model is
"MSI GE75 Raider" btw

**Comment by chriskosinski** [comment]
I suggest you give acpi_ec a try instead of ec_sys: https://github.com/musikid/acpi_ec

**Comment by thecodsman** [comment]
I tried it before but then I realised I never actually loaded it with modprobe. now it works lol
