### ISSUE TITLE
MSI Stealth 15m ASEK211

### ISSUE THREAD

**Issue by fungalspores** [dmitry-s93/MControlCenter#18]
MSI Stealth 15m ASEK211
EC VERSION: 1562EMS1.115

Cooler boost: work great

Battery: work great

FN -> SUPER: work great
Backlight keyboard: don't work

Waiting for modes and maybe I can help you with my keyboard

**Comment by dmitry-s93** [comment]
Hello. Can you please attach the EC dump of your laptop?

Describe the possible brightness levels and keyboard backlight modes (It is advisable to attach a dump for each mode).

**Comment by fungalspores** [comment]
> Hello. Can you please attach the EC dump of your laptop?
> 
> Describe the possible brightness levels and keyboard backlight modes (It is advisable to attach a dump for each mode).

How can I do EC dump?

**Comment by fungalspores** [comment]
EC dump 
       00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
000000 00 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000020 00 00 00 00 00 00 00 00 0a 05 00 00 00 04 0b 0b  >................<
000030 03 09 00 0d 01 00 50 81 f8 11 88 2c cc 01 e0 00  >......P....,....<
000040 00 00 5d 00 91 0b 00 00 c0 0a d8 2f f1 0b 00 00  >..]......../....<
000050 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000060 00 00 00 00 00 00 00 00 5c 00 3c 41 46 50 52 58  >........\.<AFPRX<
000070 64 50 00 2d 3c 46 50 50 50 00 03 03 03 03 03 03  >dP.-<FPPP.......<
000080 00 00 37 3c 46 50 52 57 63 00 00 3c 41 46 4b 50  >..7<FPRWc..<AFKP<
000090 5a 46 08 03 03 03 03 05 02 0f 7d 06 0a 78 28 00  >ZF........}..x(.<
0000a0 31 35 36 32 45 4d 53 31 2e 31 31 35 30 36 32 35  >1562EMS1.1150625<
0000b0 32 30 32 31 31 34 3a 30 34 3a 32 31 00 00 00 00  >202114:04:21....<
0000c0 00 00 07 25 00 00 00 00 00 77 00 7c 00 00 00 00  >...%.....w.|....<
0000d0 00 00 c1 83 0d 00 05 80 00 01 00 00 00 00 00 00  >................<
0000e0 e2 00 00 91 0b 00 00 40 00 00 00 80 00 cf 00 bc  >.......@........<
0000f0 02 00 7f 00 2f 64 00 00 64 00 00 00 00 00 00 00  >..../d..d.......<
000100

Profile dump 
Value       set @ address        Fan mode
0x2f(47)    0xf4(byte244)        Unknown

Value       set @ address        Charging below - stop @
0xbc(188)   0xef(byte239)        50% - 60%

-----------CPU-----------        -----------GPU-----------
Value       set @ address        Value       set @ address
0x3c(60°C)  0x6a(byte106)        0x37(55°C)  0x82(byte130)
0x41(65°C)  0x6b(byte107)        0x3c(60°C)  0x83(byte131)
0x46(70°C)  0x6c(byte108)        0x46(70°C)  0x84(byte132)
0x50(80°C)  0x6d(byte109)        0x50(80°C)  0x85(byte133)
0x52(82°C)  0x6e(byte110)        0x52(82°C)  0x86(byte134)
0x58(88°C)  0x6f(byte111)        0x57(87°C)  0x87(byte135)

0x0(0%)     0x72(byte114)        0x0(0%)     0x8a(byte138)
0x2d(45%)   0x73(byte115)        0x3c(60%)   0x8b(byte139)
0x3c(60%)   0x74(byte116)        0x41(65%)   0x8c(byte140)
0x46(70%)   0x75(byte117)        0x46(70%)   0x8d(byte141)
0x50(80%)   0x76(byte118)        0x4b(75%)   0x8e(byte142)
0x50(80%)   0x77(byte119)        0x50(80%)   0x8f(byte143)
0x50(80%)   0x78(byte120)        0x5a(90%)   0x90(byte144)

**Comment by fungalspores** [comment]
I use isw with that command `sudo isw -cp MSI_ADDRESS_DEFAULT`

**Comment by dmitry-s93** [comment]
Execute command "sudo hexdump -C /sys/kernel/debug/ec/ec0/io" and copy the output

**Comment by dmitry-s93** [comment]
> > Hello. Can you please attach the EC dump of your laptop?
> > 
> > Describe the possible brightness levels and keyboard backlight modes (It is advisable to attach a dump for each mode).
> 
> How can I do EC dump?

Execute command "sudo hexdump -C /sys/kernel/debug/ec/ec0/io" and copy the output

**Comment by fungalspores** [comment]
> > > Hello. Can you please attach the EC dump of your laptop?
> > > Describe the possible brightness levels and keyboard backlight modes (It is advisable to attach a dump for each mode).
> > 
> > 
> > How can I do EC dump?
> 
> Execute command "sudo hexdump -C /sys/kernel/debug/ec/ec0/io" and copy the output

I don't have ec folder in debug

```
root@fungal:/sys/kernel/debug# ls -a
.                 dri                 kvm               sleep_time
..                dynamic_debug       mce               sof
acpi              energy_model        mei0              soundwire
asoc              error_injection     mmc0              split_huge_pages
bdi               extfrag             opp               suspend_stats
block             fault_around_bytes  pinctrl           swiotlb
bluetooth         frontswap           pkg_temp_thermal  sync
cec               gpio                pmc_core          thunderbolt
cleancache        hid                 pm_genpd          tracing
clear_warn_once   ieee80211           pwm               ttm
clk               intel_lpss          ras               usb
devfreq           intel_powerclamp    regmap            virtio-ports
device_component  interconnect        regulator         wakeup_sources
devices_deferred  iosf_sb             remoteproc        x86
dma_buf           iwlwifi             resctrl           zswap
dmaengine         kfence              sched
dma_pools         kprobes             slab

```

**Comment by dmitry-s93** [comment]
> > > > Hello. Can you please attach the EC dump of your laptop?
> > > > Describe the possible brightness levels and keyboard backlight modes (It is advisable to attach a dump for each mode).
> > > 
> > > 
> > > How can I do EC dump?
> > 
> > Execute command "sudo hexdump -C /sys/kernel/debug/ec/ec0/io" and copy the output
> 
> I don't have ec folder in debug
> 
> ```
> root@fungal:/sys/kernel/debug# ls -a
> .                 dri                 kvm               sleep_time
> ..                dynamic_debug       mce               sof
> acpi              energy_model        mei0              soundwire
> asoc              error_injection     mmc0              split_huge_pages
> bdi               extfrag             opp               suspend_stats
> block             fault_around_bytes  pinctrl           swiotlb
> bluetooth         frontswap           pkg_temp_thermal  sync
> cec               gpio                pmc_core          thunderbolt
> cleancache        hid                 pm_genpd          tracing
> clear_warn_once   ieee80211           pwm               ttm
> clk               intel_lpss          ras               usb
> devfreq           intel_powerclamp    regmap            virtio-ports
> device_component  interconnect        regulator         wakeup_sources
> devices_deferred  iosf_sb             remoteproc        x86
> dma_buf           iwlwifi             resctrl           zswap
> dmaengine         kfence              sched
> dma_pools         kprobes             slab
> 
> ```

Just execute "sudo modprobe ec_sys write_support=1" or run MControlCenter app before execution "sudo hexdump -C /sys/kernel/debug/ec/ec0/io"

**Comment by fungalspores** [comment]
> > > > > Hello. Can you please attach the EC dump of your laptop?
> > > > > Describe the possible brightness levels and keyboard backlight modes (It is advisable to attach a dump for each mode).
> > > > 
> > > > 
> > > > How can I do EC dump?
> > > 
> > > 
> > > Execute command "sudo hexdump -C /sys/kernel/debug/ec/ec0/io" and copy the output
> > 
> > 
> > I don't have ec folder in debug
> > ```
> > root@fungal:/sys/kernel/debug# ls -a
> > .                 dri                 kvm               sleep_time
> > ..                dynamic_debug       mce               sof
> > acpi              energy_model        mei0              soundwire
> > asoc              error_injection     mmc0              split_huge_pages
> > bdi               extfrag             opp               suspend_stats
> > block             fault_around_bytes  pinctrl           swiotlb
> > bluetooth         frontswap           pkg_temp_thermal  sync
> > cec               gpio                pmc_core          thunderbolt
> > cleancache        hid                 pm_genpd          tracing
> > clear_warn_once   ieee80211           pwm               ttm
> > clk               intel_lpss          ras               usb
> > devfreq           intel_powerclamp    regmap            virtio-ports
> > device_component  interconnect        regulator         wakeup_sources
> > devices_deferred  iosf_sb             remoteproc        x86
> > dma_buf           iwlwifi             resctrl           zswap
> > dmaengine         kfence              sched
> > dma_pools         kprobes             slab
> > ```
> 
> Just execute "sudo modprobe ec_sys write_support=1" or run MControlCenter app before execution "sudo hexdump -C /sys/kernel/debug/ec/ec0/io"

00000000  00 80 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000020  00 00 00 00 00 00 00 00  0a 05 00 00 00 04 0b 0b  |................|
00000030  03 09 00 0d 01 00 50 81  f8 11 88 2c cc 01 e0 00  |......P....,....|
00000040  00 00 5d 00 91 0b 00 00  be 0a d1 2f f4 0b 00 00  |..]......../....|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000060  00 00 00 00 00 00 00 00  2f 00 41 46 4d 50 53 58  |......../.AFMPSX|
00000070  64 41 41 37 37 55 55 64  64 00 03 03 03 03 03 03  |dAA77UUdd.......|
00000080  00 00 41 46 4d 50 53 58  63 41 41 46 55 5c 64 64  |..AFMPSXcAAFU\dd|
00000090  64 46 08 03 03 03 03 05  00 0f 7d 06 0a 78 00 00  |dF........}..x..|
000000a0  31 35 36 32 45 4d 53 31  2e 31 31 35 30 36 32 35  |1562EMS1.1150625|
000000b0  32 30 32 31 31 34 3a 30  34 3a 32 31 00 00 00 00  |202114:04:21....|
000000c0  00 00 01 2f 00 00 00 00  00 c1 00 7c 00 00 00 00  |.../.......|....|
000000d0  00 00 c1 83 0d 00 05 80  00 01 00 00 00 00 00 00  |................|
000000e0  e2 00 00 91 0b 00 00 40  00 00 00 80 00 82 00 e4  |.......@........|
000000f0  00 00 7f 00 2a 64 00 00  64 00 00 00 00 00 00 00  |....*d..d.......|
00000100

**Comment by dmitry-s93** [comment]
Please clarify, only changing the backlight mode does not work? Does the brightness change when moving the brightness slider?

**Comment by dmitry-s93** [comment]
Does your laptop have RGB lighting? It is possible that the keyboard backlight is not controlled via EC.

**Comment by fungalspores** [comment]
> Does your laptop have RGB lighting? It is possible that the keyboard backlight is not controlled via EC.

Yes, rgb backlight is present, but for example OPENRGB does not work with it

**Comment by dmitry-s93** [comment]
Have you tried this command-line tool?
https://github.com/Koromix/rygel/tree/master/src/meestic

**Comment by fungalspores** [comment]
> Have you tried this command-line tool? https://github.com/Koromix/rygel/tree/master/src/meestic

I have this error

`Error: Cannot find Mystic Light HID device (1462:1563 or 1462:1564)`
