### ISSUE TITLE
Installation error: sudo ./intall: command not found.

### ISSUE THREAD

**Issue by Beallbell** [dmitry-s93/MControlCenter#185]
On following the installation instructions the command "sudo ./install" results in an error: sudo ./install command not found. 

I'm pretty new to Linux, and am using Linux Mint XFCE on a Katana GF66 11UE.

This is the code I ran in the terminal

`beallbell@C:~/Downloads$ tar -xzvf MControlCenter-0.4.1-bin.tar.gz
MControlCenter-0.4.1-bin/
MControlCenter-0.4.1-bin/app/
MControlCenter-0.4.1-bin/app/mcontrolcenter
MControlCenter-0.4.1-bin/app/mcontrolcenter-helper
MControlCenter-0.4.1-bin/app/mcontrolcenter-helper.conf
MControlCenter-0.4.1-bin/app/mcontrolcenter.helper.service
MControlCenter-0.4.1-bin/app/mcontrolcenter.desktop
MControlCenter-0.4.1-bin/app/mcontrolcenter.svg
MControlCenter-0.4.1-bin/install.sh
MControlCenter-0.4.1-bin/uninstall.sh

beallbell@C:~/Downloads$ pwd
/home/beallbell/Downloads

beallbell@C:~/Downloads$ ls
firefoxlogo.png             MControlCenter-0.4.1-bin.tar.gz
IMG_20240629_134558645.jpg  mysuperduperfile
MControlCenter-0.4.1-bin

beallbell@C:~/Downloads$ cd MControlCenter-0.4.1-bin

beallbell@C:~/Downloads/MControlCenter-0.4.1-bin$ sudo ./install
[sudo] password for beallbell:           
sudo: ./install: command not found

beallbell@C:~/Downloads/MControlCenter-0.4.1-bin$ sudo bin/install
[sudo] password for beallbell:           
sudo: bin/install: command not found`

Thank you in advance.

**Comment by rubberocket** [comment]
you have to cd into the directory (in this case MControlCenter-0.4.1-bin in the downloads folder) and type in sudo ./install.sh. Not sudo install or sudo bin/install.

**Comment by Beallbell** [comment]
Thank you! It's installed and working wonderfully now.

**Comment by rubberocket** [comment]
Don't forget to close this issue if it's solved.
