### ISSUE TITLE
MSI Summit E16 Flip (A12UCT model)

### ISSUE THREAD

**Issue by rottenpants466** [dmitry-s93/MControlCenter#19]
MY LAPTOP

- Laptop: MSI Summit E16 Flip, model A12UCT
- EC Version: E1592IMS.10C
- EC Build: 19/08/2022
- Kubuntu 22.10, kernel 6.1 RC3
- MControlCenter 0.3.0

MY TEST

- Cooler Boost: **Works!**
- Modes (High Performance, Balanced, etc): **Works!**
- Battery (Best for mobility, balanced, etc): **Works!**
- Keyboard backlight adjustment/Auto 10 second off : **Works!**
- FN -> Super: **Works!**
- Webcam: **Works!**
- USB Power share: **Works!**

Some keyboard special keys don't work: turn on/off touchpad, turn on/off mic, turn on/off webcam, changing between power modes, screen rotation.

Also fliping the screen doens't turn off the trackpad and keyboard, light sensor doens't apear to be working.

**Comment by dmitry-s93** [comment]
Hello.

Can you mark the working/not working features on your laptop in the following list?

Mode
Battery Limit
Cooler Boost

Settings:
Keyboard Backlit
FN -> Super
Webcam
USB Power Share

**Comment by rottenpants466** [comment]
- Tested the power modes with speedometer on firefox and these are the results:

> High performance score: 238
> Super battery score: 165
> 
> Using the command above there was a reduction on cpu frequency so i guess it's working. 

- The webcam option is greyed out.

- Usb power share is not working

> Enabling or disabling the option doesn't do anything when the laptop is in sleep or turned off. Also MControlCenter doens't save the setting, for example if i turn off usb sharing and close the app and then open the app again the option is still on (and vice versa).

**Comment by dmitry-s93** [comment]
> * Usb power share is not working:

On my laptop, this setting works, but is reset after shutdown or reboot (will be fixed in the future).

I turn off "Usb Power Share" and then turn off the laptop. Charging via USB does not work. After turning on the laptop "Usb Power Share" is active again. After the laptop is turned off again, charging via USB goes on.

> if i turn off usb sharing and close the app and then open the app again the option is still on

Does the option reset without rebooting the laptop?

**Comment by rottenpants466** [comment]
> > * Usb power share is not working:
> 
> On my laptop, this setting works, but is reset after shutdown or reboot (will be fixed in the future).
> 
> I turn off "Usb Power Share" and then turn off the laptop. Charging via USB does not work. After turning on the laptop "Usb Power Share" is active again. After the laptop is turned off again, charging via USB goes on.
> 
> > if i turn off usb sharing and close the app and then open the app again the option is still on
> 
> Does the option reset without rebooting the laptop?

I'm dual booting windows because of work and i think it's messing up something when i'm trying to test things (i have msi center pro installed there :| ). So, to test things properly i just tested again with a spare nvem drive with only kubuntu installed.

Now i'm getting the same exact behaviour as you. The setting works but after rebooting or turning off the laptop it resets and the usb share is active again.

**Comment by dmitry-s93** [comment]
At the moment, the application does not restore settings after a reboot. This will be fixed soon. You will need to add the application to autorun.

**Comment by dmitry-s93** [comment]
Could you check on the new version (0.3.0) of the application?
The webcam option and saving the settings should work

To restore settings after a reboot, add MControlCenter to startup:
`cp /usr/share/applications/mcontrolcenter.desktop ~/.config/autostart/mcontrolcenter.desktop`

**Comment by rottenpants466** [comment]
Can report that it works :)

Amazing job!
