### ISSUE TITLE
Cannot start installation

### ISSUE THREAD

**Issue by FrzGun** [dmitry-s93/MControlCenter#21]
Hi,
Thanks for your work 

I have a problem when im trying to install the app.

When a I run the script its says ./build/mcontrolcenter : no file or directory with this name 

What is the problem ?

thanks

**Comment by dmitry-s93** [comment]
Hi. Check that you have opened a terminal in the MControlCenter-0.1.2 directory and the mcontrolcenter file exists in the build directory.

**Comment by FrzGun** [comment]
![MControlCenter](https://user-images.githubusercontent.com/115505719/195024008-389ad4fc-ffdc-4f3f-8ad6-9ba5091f946e.png)

I dont see it 

thanks

**Comment by dmitry-s93** [comment]
You have downloaded the archive with the source code. To install you need the archive MControlCenter-0.1.2.tar.gz

**Comment by FrzGun** [comment]
Yes my bad ahah thanks
