### ISSUE TITLE
Tryint to Install this but getting a error 

### ISSUE THREAD

**Issue by Dueel** [dmitry-s93/MControlCenter#26]
When I have tried to install this on my MSI GE76 on Arch Linux I get this error: (Last line being the error)
```
Installation start
'./app/mcontrolcenter' -> '/usr/bin/mcontrolcenter'
mode of '/usr/bin/mcontrolcenter' retained as 0755 (rwxr-xr-x)
'./app/mcontrolcenter.desktop' -> '/usr/share/applications/mcontrolcenter.desktop'
mode of '/usr/share/applications/mcontrolcenter.desktop' retained as 0644 (rw-r--r--)
'./app/mcontrolcenter.svg' -> '/usr/share/icons/hicolor/scalable/apps/mcontrolcenter.svg'
mode of '/usr/share/icons/hicolor/scalable/apps/mcontrolcenter.svg' retained as 0644 (rw-r--r--)
'./app/mcontrolcenter-helper' -> '/usr/libexec/mcontrolcenter-helper'
mode of '/usr/libexec/mcontrolcenter-helper' retained as 0755 (rwxr-xr-x)
'./app/mcontrolcenter-helper.conf' -> '/etc/dbus-1/system.d/'
cp: cannot create regular file '/etc/dbus-1/system.d/': No such file or directory
```

And if I was to open the app it is in a frozen like state where I cannot click any options other than the tabs.

**Comment by dmitry-s93** [comment]
Hello

Please check if the **/usr/share/dbus-1/system.d/** directory exists?
If the directory exists, then replace **DBUS_SYSTEM_PATH='/etc/dbus-1/system.d/'** in the **install.sh** script with **DBUS_SYSTEM_PATH='/usr/share/dbus-1/system.d/'**.
Execute the **install.sh** and report the result.

**Comment by dmitry-s93** [comment]
You can re-download the installer and check.

**Comment by Dueel** [comment]
It is working! Thank you.

**Comment by Dueel** [comment]
My bad I accidentally clicked cloud with comment but if you would like to add it is all working on the GE76 Raider 11UE REV and the MSI Prestige EVO 14 (If you need any more info I am happy to help!
