### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by husujo** [dmitry-s93/MControlCenter#49]
Hi :) I cloned and tried to install (on ubuntu), 2 different ways. Not sure if the README is up to date, or I am missing something?

husujo@MSI-Alpha-15:~/MControlCenter$ sudo ./install
sudo: ./install: command not found

husujo@MSI-Alpha-15:~/MControlCenter$ sudo ./scripts/install.sh 
Installation start
cp: cannot stat './app/mcontrolcenter': No such file or directory

**Comment by dmitry-s93** [comment]
Hi. To install from the archive, you need to download MControlCenter-x.x.x.tar.gz from [here](https://github.com/dmitry-s93/MControlCenter/releases).

**Comment by burd1** [comment]
> Hi :) I cloned and tried to install (on ubuntu), 2 different ways. Not sure if the README is up to date, or I am missing something?
> 
> husujo@MSI-Alpha-15:~/MControlCenter$ sudo ./install sudo: ./install: command not found
> 
> husujo@MSI-Alpha-15:~/MControlCenter$ sudo ./scripts/install.sh Installation start cp: cannot stat './app/mcontrolcenter': No such file or directory

i have it running on pop os which is ubuntu based just fine

**Comment by husujo** [comment]
thanks, you can close this issue 😅
