### ISSUE TITLE
'FN -> Super' not working (MSI Modern A11SB)

### ISSUE THREAD

**Issue by msigurdsen** [dmitry-s93/MControlCenter#53]
Application works great. It has most features available in MSI Center Pro on Windows 10/11, except for FN -> Super which is currently greyed out and not working in MControlCenter. I've reported this in tested_devices.md.

Providing current configuration and EC dumps for additional info.

**MY LAPTOP**

Laptop: MSI Modern A11SB
OS: Pop!_OS 22.04
EC Version: 1552EMS1.120
EC Build: 01/11/2022

**CURRENT SETTINGS**

Cooler Boost: Off
Mode: Silent
Battery threshold: 60% / Best for battery
Keyboard Backlit: On (with weakest light)
Webcam: Off

**EC DUMPS**

Used MSI Center Pro on Windows to toggle FN -> Super On/Off.

**Turned ON (FN = Super):**

$ sudo hexdump -C /sys/kernel/debug/ec/ec0/io
[sudo] password for user: 

00000000  00 80 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000020  00 00 00 00 00 00 00 00  0a 05 00 00 00 04 00 0b  |................|
00000030  03 01 00 0d 00 00 50 81  f8 11 88 2c cc 01 c0 00  |......P....,....|
00000040  f8 11 3a 00 63 0d 00 00  b2 07 01 2d af 0b fa 32  |..:.c......-...2|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000060  00 00 00 00 00 00 00 00  37 00 32 3a 41 46 5a 5f  |........7.2:AFZ_|
00000070  64 41 2d 3a 41 48 50 55  64 4b 03 05 05 05 05 03  |dA-:AHPUdK......|
00000080  2c 00 32 3c 46 52 5a 5d  64 00 00 32 41 48 50 55  |,.2<FRZ]d..2AHPU|
00000090  64 46 03 05 05 06 03 03  02 00 6e 02 00 66 00 00  |dF........n..f..|
000000a0  31 35 35 32 45 4d 53 31  2e 31 32 30 30 31 31 31  |1552EMS1.1200111|
000000b0  32 30 32 32 31 35 3a 35  38 3a 34 33 00 00 00 00  |202215:58:43....|
000000c0  00 00 01 25 00 00 00 00  00 d8 00 00 00 00 00 00  |...%............|
000000d0  00 00 c1 81 1d 00 05 bc  00 01 00 00 00 00 00 00  |................|
000000e0  e2 00 00 63 0d 00 00 c1  90 00 00 80 00 c1 00 00  |...c............|
000000f0  00 00 7f 00 2a 41 37 00  41 37 00 00 00 00 00 00  |....*A7.A7......|
00000100

**Turned OFF (FN = FN):**

$ sudo hexdump -C /sys/kernel/debug/ec/ec0/io
[sudo] password for user: 

00000000  00 80 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000020  00 00 00 00 00 00 00 00  0a 05 00 00 00 04 00 0b  |................|
00000030  03 01 00 0d 00 00 50 81  f8 11 88 2c cc 01 c0 00  |......P....,....|
00000040  f8 11 3a 00 63 0d 00 00  b2 07 0b 2d be 0b fa 32  |..:.c......-...2|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000060  00 00 00 00 00 00 00 00  38 00 32 3a 41 46 5a 5f  |........8.2:AFZ_|
00000070  64 41 2d 3a 41 48 50 55  64 4b 03 05 05 05 05 03  |dA-:AHPUdK......|
00000080  2e 00 32 3c 46 52 5a 5d  64 00 00 32 41 48 50 55  |..2<FRZ]d..2AHPU|
00000090  64 46 03 05 05 06 03 03  02 00 6e 02 00 66 00 00  |dF........n..f..|
000000a0  31 35 35 32 45 4d 53 31  2e 31 32 30 30 31 31 31  |1552EMS1.1200111|
000000b0  32 30 32 32 31 35 3a 35  38 3a 34 33 00 00 00 00  |202215:58:43....|
000000c0  00 00 01 25 00 00 00 00  00 ce 00 00 00 00 00 00  |...%............|
000000d0  00 00 c1 81 1d 00 05 bc  00 01 00 00 00 00 00 00  |................|
000000e0  e2 00 00 63 0d 00 00 c1  80 00 00 80 00 c1 00 00  |...c............|
000000f0  00 00 7f 00 2c 41 37 00  41 37 00 00 00 00 00 00  |....,A7.A7......|
00000100

**Comment by dmitry-s93** [comment]
Can you check on the application in the [mcontrolcenter.tar.gz](https://github.com/dmitry-s93/MControlCenter/files/9903931/mcontrolcenter.tar.gz) archive?

**Comment by msigurdsen** [comment]
That made it work perfectly. Great job!

**Comment by msigurdsen** [comment]
Reopening as I realized you might want to have this issue opened till you've merged with main. Sorry about that!

**Comment by msigurdsen** [comment]
So FN -> Super works now all of a sudden, on the current MControlCenter release (0.3.0) without using the fix that you provided above.

Not sure what fixed it, as I both received a Linux kernel update (6.0.3), and had the EC reset after my laptop's battery depleted, earlier today. So not sure whether it was the update of the kernel or the reset of the EC that did the trick.

Might also note that mcontrolcenter.desktop now finally shows the MControlCenter icon, instead of just the placeholder cog, in the application menu. This happened simultaneously with the FN -> Super starting to work.

Don't know if it's useful but here's another EC dump:

00000000  00 80 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000020  00 00 00 00 00 00 00 00  0a 05 00 00 00 04 09 0b  |................|
00000030  03 03 00 0d 00 00 50 81  f8 11 88 2c cc 01 90 00  |......P....,....|
00000040  f8 11 0d 00 98 0d fe 10  ac 01 05 31 d6 0b fa 32  |...........1...2|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000060  00 00 00 00 00 00 00 00  3b 00 32 3a 41 46 5a 5f  |........;.2:AFZ_|
00000070  64 41 2d 3a 41 48 50 55  64 4b 03 05 05 05 05 03  |dA-:AHPUdK......|
00000080  2e 00 32 3c 46 52 5a 5d  64 00 00 32 41 48 50 55  |..2<FRZ]d..2AHPU|
00000090  64 46 03 05 05 06 03 03  02 00 6e 02 00 66 00 00  |dF........n..f..|
000000a0  31 35 35 32 45 4d 53 31  2e 31 32 30 30 31 31 31  |1552EMS1.1200111|
000000b0  32 30 32 32 31 35 3a 35  38 3a 34 33 00 00 00 00  |202215:58:43....|
000000c0  00 00 07 00 00 00 00 00  00 cb 00 00 00 00 00 00  |................|
000000d0  00 00 c1 81 1d 00 05 bc  00 01 00 00 00 00 00 00  |................|
000000e0  e2 00 00 98 0d 00 00 c1  00 00 00 80 00 c1 00 00  |................|
000000f0  00 00 7f 00 2b 41 37 00  41 37 00 00 00 00 00 00  |....+A7.A7......|
00000100

**Comment by dmitry-s93** [comment]
In the previous dump, you had a non-standard parameter value. In the current dump, the value is standard, so the function works without using the fix.

**Comment by dmitry-s93** [comment]
> Might also note that mcontrolcenter.desktop now finally shows the MControlCenter icon, instead of just the placeholder cog, in the application menu. This happened simultaneously with the FN -> Super starting to work.

Most likely, when updating the system, the icon cache was updated and the application icon began to be displayed

**Comment by msigurdsen** [comment]
You learn something new every day...
