### ISSUE TITLE
Testing MControlCenter on Fedora 37

### ISSUE THREAD

**Issue by rottenpants466** [dmitry-s93/MControlCenter#66]
Hi, i was testing this on the latest Fedora 37 release and it seems it doesn't work. McontrolCenter tries to enable the ec_sys module but it fails. It seems that this particular module is not available in the Fedora kernel.

Are there any workarounds for this?

Thank you dmitry

**Comment by dmitry-s93** [comment]
Hi. Fedora does not include the ec_sys module in the normal kernel. The easiest way is to install kernel-debug or use a different distribution. You can also try to use https://github.com/MusiKid/acpi_ec, but it will require some tweaking in MControlCenter.

**Comment by rottenpants466** [comment]
See if i can try that. One question not related to this dmitry: does your laptop works in tablet mode? i mean does it disable de keyboard and mouse when you flip the screen?

Thank you

**Comment by dmitry-s93** [comment]
The touchpad and keyboard do not turn off when the screen is flipped. Automatic orientation change works if enabled in the settings.

**Comment by rottenpants466** [comment]
> The touchpad and keyboard do not turn off when the screen is flipped. Automatic orientation change works if enabled in the settings.

Ok, im getting some help with that in the libinput bug tracker: https://gitlab.freedesktop.org/libinput/libinput/-/issues/822

Im currently rebuilding the kernel with the patch provided there and will se if that fixes this particular isse on our laptops and maybe help other people too in the process

**Comment by rottenpants466** [comment]
> Hi. Fedora does not include the ec_sys module in the normal kernel. The easiest way is to install kernel-debug or use a different distribution. You can also try to use https://github.com/MusiKid/acpi_ec, but it will require some tweaking in MControlCenter.

Regarding fedora again. Tried to install the acpi_ec like you mentioned but the error `Failed to load the ec_sys kernel module`. In order to suport fedora (and other distros) that don't have the ec_sys module does it require a lot of work? Or just changing a few lines in the code?

Thank you dmitry!

**Comment by dmitry-s93** [comment]
> why it does only work using apps like yours?
Support in the Linux kernel for MSI laptops is not implemented.

> Tried to install the acpi_ec like you mentioned but i get the error
Try to execute "sudo hexdump -C /dev/ec". If it works, I will build an application with a fix for acpi_ec to work.

**Comment by rottenpants466** [comment]
I installed it using this guide: https://github.com/YoyPa/isw/issues/265#issue-1419231642

```
sudo -i
cd /opt
git clone https://github.com/musikid/acpi_ec.git
cd acpi_ec
# Make sure your env is clean
./uninstall.sh &>/dev/null
apt remove -y acpi-ec 2>/dev/null
# Perform installation
./install.sh
```

I could not install using `sudo ./install.sh` from here: https://github.com/musikid/acpi_ec

Anyway, i dont see the ec folder in/dev

![Screenshot_20221126_011604](https://user-images.githubusercontent.com/62076029/204066999-606271d8-6fc6-4b4c-bb9d-e62dbc846363.png)

**Comment by rottenpants466** [comment]
Oh i found this ec file in dev after all , is this what you wanted?

![Screenshot_20221126_120942](https://user-images.githubusercontent.com/62076029/204088160-4d66f88e-a646-44ac-8be6-5aaf7e2acfa5.png)

```
[andre@SummitE16Flip dev]$ sudo hexdump -C /dev/ec
[sudo] senha para andre: 
00000000  00 80 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000020  00 00 00 00 00 00 00 00  0a 05 00 80 80 0c 0b 0a  |................|
00000030  07 01 00 05 00 00 50 81  a0 14 60 3b 10 02 c0 00  |......P...`;....|
00000040  18 15 37 00 49 14 00 00  27 0b 46 3c 79 0b f8 43  |..7.I...'.F<y..C|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000060  00 00 00 00 00 00 00 00  23 00 3c 46 50 55 5a 5f  |........#.<FPUZ_|
00000070  64 2d 2d 37 3c 46 5a 6e  82 00 0a 08 08 03 03 03  |d--7<FZn........|
00000080  00 00 37 41 4b 55 59 5a  59 2d 2d 46 5a 64 6e 6e  |..7AKUYZY--FZdnn|
00000090  6e 00 05 03 03 08 07 03  02 00 7d 02 00 7d 20 00  |n.........}..} .|
000000a0  31 35 39 32 45 4d 53 31  2e 31 31 31 30 36 32 39  |1592EMS1.1110629|
000000b0  32 30 32 32 30 39 3a 35  32 3a 32 38 00 00 00 28  |202209:52:28...(|
000000c0  00 00 01 25 00 00 00 00  00 00 00 00 00 00 00 00  |...%............|
000000d0  00 00 c1 81 1d 00 05 bc  00 00 00 00 00 05 00 00  |................|
000000e0  e2 00 00 49 14 01 00 00  00 04 00 80 00 79 01 cb  |...I.........y..|
000000f0  00 00 70 80 20 64 00 00  64 00 00 00 00 00 00 00  |..p. d..d.......|
00000100
[andre@SummitE16Flip dev]$ 
```

**Comment by dmitry-s93** [comment]
> Oh i found this ec file in dev after all , is this what you wanted?

Yes

Version with acpi_ec support: [MControlCenter-0.3.1-test-build.tar.gz](https://github.com/dmitry-s93/MControlCenter/files/10096604/MControlCenter-0.3.1-test-build.tar.gz)

Check, please.

**Comment by rottenpants466** [comment]
Just tested dmitry!

The app opens up normaly and almost everything works!

The only thing that doesn't work is the battery thresholds:

![Screenshot_20221127_004036](https://user-images.githubusercontent.com/62076029/204114176-51d0249b-f897-4aab-b5dd-c05004854321.png)
(Example, Battery mode set to `Best for mobility` but it says `Not charging`. Also the little led on the right of the laptop doens't turn on).

**Comment by dmitry-s93** [comment]
Do laptop settings apply?  For example, try enabling Cooler Boost.

**Comment by rottenpants466** [comment]
Yes they apply

**Comment by dmitry-s93** [comment]
> Everything seems to be working minus the battery thresholds.

You have data at both possible addresses 0xD7 and 0xEF. This may be due to the use of software that does not support changing the battery limit on this laptop model. Reset the EC and the charge limit will work. 
https://www.msi.com/support/technical_details/NB_EC_RESET


> i just added MControlCenter in the start-up settings and it was enough

The command in the terminal does the same

**Comment by rottenpants466** [comment]
It works  :+1: 

Had to reset the EC
