### ISSUE TITLE
Issue with Install

### ISSUE THREAD

**Issue by acmelhorn** [dmitry-s93/MControlCenter#80]
I am trying to install the application on POP OS and running into some issues.  First error:
`Installation start
cp: cannot stat './app/mcontrolcenter': No such file or directory`

Looking reading install.sh, I see that the filenames and structure listed in the script do not match those in the repository.  Am I missing something?  Do I need to relabel all the files and directories to match?

Apologies if I am missing something obvious.  I know just enough to get me in trouble most of the time.

**Comment by dmitry-s93** [comment]
Hello. To install app from the archive, you need to download MControlCenter-x.x.x.tar.gz from [here](https://github.com/dmitry-s93/MControlCenter/releases).

**Comment by acmelhorn** [comment]
I knew it was something obvious.  Thank you!  I was able to install and use the app with no issues.
