### ISSUE TITLE
MSI GF63-Thin-11UC-866IN

### ISSUE THREAD

**Issue by soumyatheman** [dmitry-s93/MControlCenter#81]
Well, Firstly this control center is almost close to the dragon center, and it's really very good. In my laptop, almost all the options  work, only the auto off of the keyboard backlight doesn't. My problem is there are some functionalities in my Fn key row. 

**Fn+F2** = Share Screen, which I know will not work. 
**Fn+F3** = Enabling/Disabling touchpad Doesn't Work
**Fn+F6** = Enabling/Disabling webcam Works(also has a LED indicator on it which pop's up)
**Fn+F7** = Don't know what it does, doesn't understood even in Windows
**Fn+F10** = Airplane mode button, surprisingly doesn't work
**Fn+F12** = Suspend mode, which works with my surprise

Any ways to enable atleast the airplane mode option? What should I try, can u give me some ray of hope?

**Comment by dmitry-s93** [comment]
Hello. There is no way to enable FN keys using McontrolCenter.

**Comment by soumyatheman** [comment]
Well, thanks, anyway to add the fan control support?
Also, is there an airplane-mode key in your laptop?

**Comment by dmitry-s93** [comment]
> Well, thanks, anyway to add the fan control support?

Fan speed control in development. I can't say when it will be ready. For now, I don't have much free time.

> Also, is there an airplane-mode key in your laptop?

No
