### ISSUE TITLE
Add: MSI GF63 11UC-866IN

### ISSUE THREAD

**Issue by soumyaDghosh** [dmitry-s93/MControlCenter#83]
Add this in the tested devices list

**Comment by soumyaDghosh** [comment]
MControl Center, what's working

1. Fan Speeds: As there is only one fan, so it shows the data of only one fan. I guess the second one can be disabled from showing.
2. Cooler Boost: Works completely fine
3. Performance Mode: All works
4. Battery Modes: Didn't checked custom, but all the modes work. 
5. Keyboard backlit: the brightness bar works but the auto-turn off doesn't work
6. Fn-Super interchange works
7. Webcam works
8. USB Power Share option is greyed

**Comment by soumyaDghosh** [comment]
Sorry, I had exam, so, this delay.

**Comment by soumyaDghosh** [comment]
Also a suggestion. Why don't add the touchpad toggle also?

**Comment by dmitry-s93** [comment]
Are you sure your model is GF76? On request "11UC-866IN" finds GF63. Please write EC Version and EC Build.

> Also a suggestion. Why don't add the touchpad toggle also?
I don't think it can be done with EC.

**Comment by soumyaDghosh** [comment]
> Are you sure your model is GF76? On request "11UC-866IN" finds GF63. Please write EC Version and EC Build.
Noob me

**Comment by soumyaDghosh** [comment]
>I don't think it can be done with EC.

My laptop hotkeys are one of the biggest reasons I am requesting this to u. There is a hotkey in my pc, but it gives me multiple values when tested via `evtest`. Like this

```
Event: time 1676311453.645233, type 4 (EV_MSC), code 4 (MSC_SCAN), value 1d
Event: time 1676311453.645233, type 1 (EV_KEY), code 29 (KEY_LEFTCTRL), value 1
Event: time 1676311453.645233, -------------- SYN_REPORT ------------
Event: time 1676311453.656428, type 4 (EV_MSC), code 4 (MSC_SCAN), value db
Event: time 1676311453.656428, type 1 (EV_KEY), code 125 (KEY_LEFTMETA), value 1
Event: time 1676311453.656428, -------------- SYN_REPORT ------------
Event: time 1676311453.666527, type 4 (EV_MSC), code 4 (MSC_SCAN), value 76
Event: time 1676311453.666527, type 1 (EV_KEY), code 85 (KEY_ZENKAKUHANKAKU), value 1
Event: time 1676311453.666527, -------------- SYN_REPORT ------------
Event: time 1676311453.676613, type 4 (EV_MSC), code 4 (MSC_SCAN), value 1d
Event: time 1676311453.676613, type 1 (EV_KEY), code 29 (KEY_LEFTCTRL), value 0
Event: time 1676311453.676613, -------------- SYN_REPORT ------------
Event: time 1676311453.696984, type 4 (EV_MSC), code 4 (MSC_SCAN), value db
Event: time 1676311453.696984, type 1 (EV_KEY), code 125 (KEY_LEFTMETA), value 0
Event: time 1676311453.696984, -------------- SYN_REPORT ------------
Event: time 1676311453.707102, type 4 (EV_MSC), code 4 (MSC_SCAN), value 76
Event: time 1676311453.707102, type 1 (EV_KEY), code 85 (KEY_ZENKAKUHANKAKU), value 0
Event: time 1676311453.707102, -------------- SYN_REPORT ------------
````

**Comment by dmitry-s93** [comment]
You can assign your own key combination to toggle the touchpad.

For example in KDE: System Settings -> Shortcuts -> Touchpad

Please tell me the EC Version and EC Build that the application shows. I'll add it to the list of tested devices.

**Comment by soumyaDghosh** [comment]
![image](https://user-images.githubusercontent.com/72045785/218549821-2eeda787-dd31-431f-a32b-b4a5f56b596e.png)

**Comment by Radical4ever** [comment]
I have the same laptop but i cant use the power modes, any suggestions of how to make them able to use?, thank you
