### ISSUE TITLE
how do i set the kernel module option?

### ISSUE THREAD

**Issue by Radical4ever** [dmitry-s93/MControlCenter#95]
hi, so i have the acpi_ec module but i dont know how to change the options, any tutorial of how to do that?, thank you

**Comment by dmitry-s93** [comment]
Hi. What Linux distribution are you using? Did you install the acpi_ec kernel module following the instructions from [here](https://github.com/musikid/acpi_ec)?

**Comment by dmitry-s93** [comment]
Doesn't this distribution have the ec_sys kernel module?
Try running "sudo modprobe ec_sys" in a terminal.

**Comment by Radical4ever** [comment]
drops me nothing nor i saw a file related to it while searching

**Comment by dmitry-s93** [comment]
> drops me nothing

So the module is loaded. The file should now be available at /sys/kernel/debug/ec/ec0/io.

Check if the settings are available in the MControlCenter after the command is executed.

The original problem is the error "Failed to load kernel module"?

**Comment by Radical4ever** [comment]
> > drops me nothing
> 
> So the module is loaded. The file should now be available at /sys/kernel/debug/ec/ec0/io.
> 
> Check if the settings are available in the MControlCenter after the command is executed.
> 
> The original problem is the error "Failed to load kernel module"?

No, the original issue was that i didnt know the path to the module, im trying that asap i get back from work. Thank you!

**Comment by Radical4ever** [comment]
I tried installing it directly skipping adding the lines in the module option, but it cannot be started, on a few hours i leave the output for any support identifying that, but i will try modifying the module option

**Comment by dmitry-s93** [comment]
You don't need the acpi_ec kernel module if "sudo modprobe ec_sys" works on your distribution. Please describe the problem in more detail.

**Comment by Radical4ever** [comment]
> You don't need the acpi_ec kernel module if "sudo modprobe ec_sys" works on your distribution. Please describe the problem in more detail.

i start the program from its desktop file and it drops me the next issue when i execute it in terminal

`root@msi-vanilla:/usr/share/applications# ./mcontrolcenter.desktop
./mcontrolcenter.desktop: línea 1: [Desktop: orden no encontrada
./mcontrolcenter.desktop: línea 2: Settings: orden no encontrada
./mcontrolcenter.desktop: línea 2: Utility: orden no encontrada
./mcontrolcenter.desktop: línea 5: MSI: orden no encontrada
./mcontrolcenter.desktop: línea 6: GenericName[ru]: no es un identificador válido
./mcontrolcenter.desktop: línea 6: настроек: orden no encontrada
./mcontrolcenter.desktop: línea 7: GenericName[pt]: no es un identificador válido
./mcontrolcenter.desktop: línea 7: Definições: orden no encontrada
./mcontrolcenter.desktop: línea 8: GenericName[es]: no es un identificador válido
./mcontrolcenter.desktop: línea 8: los: orden no encontrada
./mcontrolcenter.desktop: línea 9: GenericName[nb]: no es un identificador válido
./mcontrolcenter.desktop: línea 9: innstillinger: orden no encontrada
./mcontrolcenter.desktop: línea 10: GenericName[tr]: no es un identificador válido
./mcontrolcenter.desktop: línea 10: Laptop: orden no encontrada
./mcontrolcenter.desktop: línea 11: GenericName[pt_br]: no es un identificador válido
./mcontrolcenter.desktop: línea 11: Definições: orden no encontrada
./mcontrolcenter.desktop: línea 12: GenericName[it]: no es un identificador válido
`

**Comment by dmitry-s93** [comment]
What does it show when you run the "mcontrolcenter" command in the terminal?

**Comment by Radical4ever** [comment]
There, i managed to make it work!, on Vanilla os you must restart to apply all changes(my bad 😅🤣),(on my case mcontrolcenter) its works great on my gf63 thin the only thing that i cant change are the power profiles but the resr works exellent. Thank you for answer me all this time

**Comment by Radical4ever** [comment]
> So the module is loaded. The file should now be available at /sys/kernel/debug/ec/ec0/io.

there is nothing here

**Comment by dmitry-s93** [comment]
> there is nothing here

The file will appear after doing "sudo modprobe ec_sys". MControlCenter tries to automatically load the ec_sys kernel module if it is not loaded.

**Comment by Radical4ever** [comment]
yup now i have the files created, but how can i add the write_support=1? if i use nano on io puts me the error that i dont have permission to write it even with sudo

**Comment by dmitry-s93** [comment]
> how can i add the write_support=1?

sudo modprobe ec_sys write_support=1

MControlCenter not loading kernel module on startup? Usually nothing needs to be done.

**Comment by Radical4ever** [comment]
> > how can i add the write_support=1?
> 
> sudo modprobe ec_sys write_support=1
> 
> MControlCenter not loading kernel module on startup? Usually nothing needs to be done.

Oh so that's it. Thank you
